baseURL = 'https://www.robel.dev.et'
languageCode = 'en-us'
title = 'Robel Abiye'
theme = 'hugo-theme-m10c'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 1
  
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2

  [[menu.main]]
    name = "Contact Me"
    url = "/contact"
    weight = 3

[params]
description = "Exploring the Intersection of Accounting and Technology"
avatar = "images/avatar.jpg"
[[params.social]]
  icon = "brand-github"
  name = "My Github"
  url = "https://github.com/RoarAbiye"
[[params.social]]
  icon = "brand-telegram"
  name = "My telegram"
  url = "https://t.me/robelabiye"
[[params.social]]
  icon = "brand-x"
  name = "My twitter"
  url = "https://x.com/RobelAbiye"
[[params.social]]
  icon = "brand-linkedin"
  name = "My twitter"
  url = "https://www.linkedin.com/in/robel-abiye/"
[[params.social]]
  icon = "brand-reddit"
  name = "My twitter"
  url = "https://www.reddit.com/u/RobelAbiye"

[[params.social]]
  icon = "brand-tiktok"
  name = "My twitter"
  url = "https://www.tiktok.com/@robeltalkstech"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      linkify = true
      typographer = true
      attributes = true
