baseURL = 'https://www.robel.dev.et'
languageCode = 'en-us'
title = 'Robel ቀላልTech'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 3
